### ISSUE TITLE
Gradient of About Card coming from wrong side

### ISSUE THREAD

**Issue by MatthewSzurkowski** [Flex-Consulting/Flex-Consulting.github.io#8]
Similarly to how I handled the left right issue in the "Our Work" section, we need to reverse the direction in which the gradient is coming from for a more cleaner look.

**Comment by Rishav1707** [comment]
![gradient](https://user-images.githubusercontent.com/97666287/214230496-3b3025ca-a357-443f-9cc5-9b58a2a23251.png)

This section `gradient`? Does this have to be reversed?

**Comment by MatthewSzurkowski** [comment]
Patch applied with [c517832](https://github.com/Flex-Consulting/Flex-Consulting.github.io/commit/c5178320f00380c37eb7359181100ba6e8e2447b) ⭐
